
feature "ZenAPI" do

  # background do
  # end

  # A user sees a random quote on the homepage, generated by the GitHup API zen endpoint.
  # If your application cannot access the GitHub API (for instance, if you have become rate limited), a user will see a quote pre-defined in your Rails app.
  scenario "visit home page and see a zen message" do
    visit root_path
    expect(find("#zen-quote").text).not_to be_empty
  end

end

# Raise your applications request celing by authenticating your application.
