development:
  access_key_id: #
  secret_access_key: #
  bucket: experiments.moodboard

test:
  access_key_id: #
  secret_access_key: #
  bucket: experiments.moodboard

production:
  access_key_id: #
  secret_access_key: #
  bucket: experiments.moodboard