# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d253655122a576da5a90af414ae5269665fcb92dd539bbde84adf8a7624bd5e8c6ec78ddfc0593d42246a80fcf8379b70960f76617383e49cc8d61c33ab03ae

test:
  secret_key_base: e76649fc334bc5d125a4488e517c2745ea4bf6df88ff076ddabb242b585f7bc77f6da17716959445f7dc2efdecaf44faebf17732becf85cd587e792b9a033ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
